name: Run unit test

on:
  push:
    branches: ['**']

permissions:
  contents: read

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies and build
        run: |
          pnpm i --frozen-lockfile
          pnpm build

      - name: Run pnpm test
        run: |
          pnpm run build
          pnpm run test
